name: manage
on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request. 
  push:
    branches:
      - main
jobs:
  sonarqube:
    name: SonarQube Trigger
    runs-on: ubuntu-latest
    steps:
    - name: Checking out
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        path: frontend
    
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      with:
         projectBaseDir: app/src
         args: >
           -Dsonar.projectKey=giri_project 
           -Dsonar.sources=. 
           -Dsonar.host.url=http://13.126.0.103:9000 
           -Dsonar.login=8de7e455c94b7d5909d2e1ea2261967c8df1abc2
         
     
  
    
        
        

